### ISSUE TITLE
Separate spigot module in commons module.

### ISSUE THREAD

**Issue by chicoferreira** [Elite-dos-Desenvolvedores/EliteNPCs#7]
Some classes on spigot module can be used by other server platforms. To reuse that code, should be created an commons module between the api and the platform implementations.

The diagram would look like this:
![image](https://user-images.githubusercontent.com/36338391/66724059-d57ee600-ee18-11e9-9281-5ddfecc43a72.png)

**Comment by TommyAlmeida** [comment]
Give an example please.
